import { format } from "mathjs";

function scientificFormat(num) {
  return format(num, { notation: "exponential", precision: 3 });
}

// original code
// export const essential_column_ids = [
//   "rsid",
//   "snp_id",
//   "snp_region",
//   "snp_chromhmm",
//   "snp_openchrom",
//   "hic_distal_bin",
//   "hic_promoter_bin",
//   "gene",
//   "strand",
//   "transcript_id",
//   "promoter",
//   "gene_chromhmm",
//   "gene_reftss",
// ];

export const essential_column_ids = ["rsid", "snp_id"];

// { rsid, snp_id, snp_region, gene, gene_distance, snp_chromhmm, snp_openchrom, snp_tf, hic_distal_bin, hic_promoter_bin, promoter_region, promoter_tx, promoter_gene, reftss, ccre, promoter_chromhmm, promoter_openchrom, maf, viewConfig, }
export const snp_columns = [
  // {
  //   id: 'rsid',
  //   label: 'rsid',
  //   minWidth: 60,
  //   color: "black",
  //   align: 'center',
  //   description: "SNP from dbSNP",
  // },
  // {
  //   id: "snp_id",
  //   label: "SNP ID",
  //   minWidth: 30,
  //   align: "center",
  //   orderDir: "asc",
  //   color: "black",
  //   description: "Posiyion",
  //   width: "20%",
  // },
  // {
  //   id: "gene",
  //   label: "Gene",
  //   minWidth: 60,
  //   align: "center",
  //   color: "black",
  //   description: "Nearest gene",
  // },
  // {
  //   id: "gene_distance",
  //   label: "Gene Distance",
  //   minWidth: 30,
  //   align: "center",
  //   color: "black",
  //   description: "Distances to nearby genes",
  // },
  // {
  //   id: "snp_chromhmm",
  //   label: "SNP ChromHMM",
  //   minWidth: 30,
  //   align: "center",
  //   color: "black",
  //   description: "ChromHMM annotation at SNP region",
  // },
  // {
  //   id: "snp_openchrom",
  //   label: "SNP OpenChrom",
  //   minWidth: 10,
  //   maxWidth: 20,
  //   align: "center",
  //   color: "black",
  //   description: "Open chromatin info at SNP region",
  // },
  // {
  //   id: "snp_tf",
  //   label: "SNP TF",
  //   minWidth: 80,
  //   align: "center",
  //   color: "black",
  //   description: "Transcription Factor at SNP region",
  // },
  // {
  //   id: "hic_distal_bin",
  //   label: "HiC Distal Bin",
  //   minWidth: 20,
  //   maxWidth: 300,
  //   align: "center",
  //   color: "red",
  //   description: "Hic distal bin",
  // },
  {
    id: "hic_promoter_bin",
    label: "HiC Promoter Bin",
    minWidth: 20,
    maxWidth: 300,
    color: "red",
    description: "HiC regulatory bin",
    align: "center",
  },

  {
    id: "promoter_region",
    label: "Promoter region",
    minWidth: 60,
    maxWidth: 500,
    color: "green",
    description: "Promoter region info",
  },
  {
    id: "promoter_tx",
    label: "promoter_tx",
    minWidth: 60,
    maxWidth: 500,
    orderDir: "asc",
    color: "green",
    format: scientificFormat,
    description: "Promoter transcript",
    align: "center",
  },
  {
    id: "promoter_gene",
    label: "promoter_gene",
    minWidth: 80,
    maxWidth: 500,
    orderDir: "asc",
    color: "green",
    description: "Promoter gene",
    align: "center",
  },
  {
    id: "promoter_chromhmm",
    label: "promoter_chromHMM",
    minWidth: 100,
    maxWidth: 300,
    color: "green",
    align: "center",
    description: "ChromHMM annotation for the regulatory bin",
  },
  {
    id: "promoter_openchrom",
    label: "promoter_openchrom",
    minWidth: 20,
    align: "center",
    color: "green",
    description: "Open chromatin info for the promoter region",
  },
  {
    id: "reftss",
    label: "RefTSS",
    minWidth: 20,
    width: "2rem",
    color: "blue",
    description: "RefTSS info for the gene",
    align: "center",
  },
  {
    id: "ccre",
    label: "CCRE",
    minWidth: 100,
    maxWidth: 300,
    color: "blue",
    align: "center",
    description: "CCRE info for the gene",
  },
];

export const gene_columns = [
  // {
  //   id: "gene",
  //   label: "Gene (TPM)",
  //   minWidth: 80,
  //   align: "center",
  //   color: "black",
  //   description: "Gene mapped by Ensembl",
  // },
  // {
  //   id: "strand",
  //   label: "Strand",
  //   minWidth: 30,
  //   align: "center",
  //   orderDir: "asc",
  //   color: "black",
  //   description: "Strand",
  // },
  {
    id: "transcript_id",
    label: "Transcript ID (TPM)",
    minWidth: 30,
    align: "center",
    orderDir: "asc",
    color: "black",
    description: "Transcript ensembl ID",
  },
  // {
  //   id: 'chr',
  //   label: 'Chr',
  //   minWidth: 30,
  //   align: 'center',
  //   orderDir: "asc",
  //   color: "black",
  //   description: "Chromosome",
  // },
  // {
  //   id: 'start',
  //   label: 'Start',
  //   minWidth: 60,
  //   align: 'center',
  //   color: "black",
  //   description: "Start position",
  // },
  // {
  //   id: 'end',
  //   label: 'End',
  //   minWidth: 60,
  //   align: 'center',
  //   color: "black",
  //   description: "End position",
  // },
  {
    id: "promoter",
    label: "Promoter",
    minWidth: 60,
    align: "center",
    color: "black",
    description: "Promoter region",
  },

  {
    id: "hic_promoter_bin",
    label: "Hi-C promoter bin",
    minWidth: 20,
    maxWidth: 150,
    color: "red",
    description: "Promoter bin",
  },
  {
    id: "hic_distal_regulatory_bin",
    label: "Hi-C distal regulatory bin",
    minWidth: 20,
    maxWidth: 150,
    orderDir: "asc",
    color: "red",
    description: "Promoter binDistal regulatory bin",
  },
  // {
  //   id: 'atac',
  //   label: 'Promoter open chromatin region',
  //   minWidth: 20,
  //   width: '2rem',
  //   color: "green",
  //   description: "Promoter open chromatin region",
  // },
  // {
  //   id: 'tf_parsed',
  //   label: 'Promoter TF motif',
  //   minWidth: 20,
  //   align: 'center',
  //   color: "green",
  //   description: "TF motif in ATAC-seq region",
  // },
  // {
  //   id: 'chromhmm_parsed',
  //   label: 'ChromHMM',
  //   minWidth: 20,
  //   width: '2rem',
  //   color: "green",
  //   description: "ChromHMM in promoter region",
  // },
  {
    id: "chromhmm",
    label: "ChromHMM",
    minWidth: 20,
    width: "2rem",
    color: "green",
    description: "ChromHMM in promoter region",
  },
  {
    id: "reftss",
    label: "RefTSS",
    minWidth: 20,
    width: "2rem",
    color: "green",
    description: "RefTSS predicted TSS",
  },
  // {
  //   id: 'tss',
  //   label: 'TSS',
  //   minWidth: 20,
  //   width: '2rem',
  //   color: "green",
  //   description: "TSS",
  // },

  {
    id: "encode_ccre",
    label: "ENCODE-cCRE",
    minWidth: 20,
    width: "2rem",
    orderDir: "desc",
    color: "green",
    description: "ccre predicted by ENCODE",
  },
  {
    id: "open_chromatin",
    label: "Open chromatin",
    minWidth: 20,
    width: "2rem",
    orderDir: "desc",
    color: "green",
    description: "Open chromatin",
  },
  {
    id: "hic_infomation",
    label: "Hi-C information",
    minWidth: 20,
    width: "2rem",
    orderDir: "desc",
    color: "green",
    description: "Hi-C information",
  },
];

//  unfinished_021221
export const disease_columns = [
  {
    id: "snp",
    label: "snp",
    minWidth: 60,
    color: "black",
    align: "center",
    description: "SNP from dbSNP",
  },
  {
    id: "snp_id",
    label: "SNP-ID",
    minWidth: 30,
    align: "center",
    orderDir: "asc",
    color: "black",
    description: "Posiyion",
    width: "20%",
  },
  {
    id: "risk_allele",
    label: "Risk allele",
    minWidth: 60,
    color: "black",
    align: "center",
    description: "Risk allele",
  },
  {
    id: "p_value",
    label: "P-value",
    minWidth: 60,
    color: "black",
    align: "center",
    description: "P value",
  },
  {
    id: "or_beta",
    label: "OR Beta",
    minWidth: 60,
    color: "black",
    align: "center",
    description: "OR Beta",
  },
  {
    id: "ci",
    label: "CI",
    minWidth: 60,
    color: "black",
    align: "center",
    description: "CI-95",
  },
  {
    id: "snp_region",
    label: "SNP region",
    // minWidth: 60,
    // maxWidth: 300,
    width: 10,
    color: "red",
    align: "center",
    description: "SNP region",
  },
  {
    id: "reported_gene",
    label: "Reported gene",
    minWidth: 60,
    color: "black",
    align: "center",
    description: "Reported gene",
  },
  {
    id: "reported_trait",
    label: "Reported trait",
    minWidth: 60,
    color: "black",
    align: "center",
    description: "Reported Trait",
  },
  {
    id: "gene",
    label: "Gene",
    minWidth: 60,
    align: "center",
    color: "black",
    description: "Nearest gene",
  },
  {
    id: "study_accession",
    label: "Study accession",
    minWidth: 60,
    color: "black",
    align: "center",
    description: "Study accession",
  },
  {
    id: "gene_distance",
    label: "Gene Distance",
    minWidth: 30,
    align: "center",
    color: "black",
    description: "Distances to nearby genes",
  },
  {
    id: "chromhmm",
    label: "chromHMM",
    minWidth: 30,
    align: "center",
    color: "black",
    description: "ChromHMM annotation at SNP region",
  },
  {
    id: "open_chromatin_region",
    label: "Open chromatin region",
    minWidth: 10,
    maxWidth: 20,
    align: "center",
    color: "black",
    description: "Open chromatin info at SNP region",
  },
  {
    id: "tf_footprinting",
    label: "TF footprinting",
    minWidth: 80,
    align: "center",
    color: "black",
    description: "Transcription Factor at SNP region",
  },
  {
    id: "hic_regulatory_bin",
    label: "Hi-C regulatory bin",
    minWidth: 20,
    maxWidth: 300,
    align: "center",
    color: "red",
    description: "Hic regulatory bin",
  },
];
