import React, { Component } from 'react'
import Button from '@material-ui/core/Button';
import Box from '@material-ui/core/Box';
import Container from '@material-ui/core/Container';

export default class Welcome extends Component {
    onButtonClick = (e) =>{
        this.props.handleWf(e);
        this.props.handleDrawerOpen();

    }

    render() {
        return (
            <Container>
                <h3 style={{fontSize:23}}> Welcome to MUSC Epigenome Browser</h3>
                <p style={{fontSize:16}}>
                <span style={{fontWeight:"bold"}}>MUSC Epigenome Browser</span> a knowledge-based portal with web-interface browser and visualization presentation to provide predicted causal genes affected by GWAS SNPs (especially for those non-coding SNPs) in GWAS loci. The Prediction is based on primary human cell-type specific gene regulatory circuits generated by HI-C seq, ATAC-seq and RNA-seq and Chip-seq. 
                </p>
                <Box>
                    <img height="250" src={require('../browser architecture.png')}></img>
                </Box>

                <p style={{fontSize:16, marginTop:40}}>
                <span style={{fontWeight:"bold"}}>Start search by clicking one of buttons below</span>
                </p>
                <Button variant="contained" color="primary" style={{fontSize:18, margin:8}} value="snp" onClick={this.onButtonClick}>
                    {/* SNP eQTL */}
                    SNP
                 </Button>
                 <Button variant="contained"  style={{fontSize:18, backgroundColor:"red", color:"white", margin:8}} value="gene" onClick={this.onButtonClick}>
                    {/* SNP eQTL */}
                    Gene
                 </Button>

                { <Button variant="contained" style={{fontSize:18, backgroundColor:"green", color:"white", margin:8}} value="disease" onClick={this.onButtonClick}>
                    Disease
                </Button> }
            </Container>
        )
    }
}
